### ISSUE TITLE
Parse header data (adapt parsing?)

### ISSUE THREAD

**Issue by torbencarstens** [woog-life/tide-provider#1]
e.g.

```
I_E#DE__510P2023# 
 A01#Hersteller :#M1103/BSH-Hamburg, 24.09.2021  11:32:47# 
 A02#Daten-Art  :#Vorausberechnungen# 
 A03#PegelNr.   :#DE__510P# 
 A04#GT-Name    :#Husum, Schleuse# 
 A06#GT-Jahr    :#      2023# 
 A07#Def.-Jahr  :#2020#19# 
 A08#Position   :#54°28'20''N   9°01'29''E WGS84# 
 A11#Zeitzone   :#UTC+ 1h00min (MEZ)# 
 A12#Position GK:# 35 01676.00 R  60 38046.00 H# 
 A13#Messstelle :#9530020 # 
 C01#Analyse-Ber:#selbstständig#        #39 39# 
 C02#Datenumfang:#Zeiten u. Höhen: HW NW      # 
 C03#Höhenniveau:#PNP# 
 C04#EinheitZeit:#StdMin# 
 C05#EinheitHöhe:# m# 
 C12#VB-Methode :#HDdU (HW/NW)# 
 D01#PNP u. NHN :#- 5.00 # 
 D02#SKN u. NHN :#- 2.46 # 
 D03#SKN ü. PNP :#  2.54 # 
 F01#MHWI       :#12:33   # 
 F02#MNWI       :#18:49   # 
 G01#MHW        :#  6.70 # 
 G02#MNW        :#  3.18 #
```

I guess some of this is rather irrelevant, e.g. `A03` is contained in every data line.

It would be interesting to know if some of these fields even have other values (e.g. `C04`, `A11`) to know whether we should include this.

And even more interesting whether this could be different for years for the same `A13` (`lake` in this project).

If we assume that some fields are always the same over years then we could attach this as metadata to the lake, this could bite us later on though.

Certain fields definitely have other values (e.g. `Fx`, `A07`), these should simply be updated. Another option would be to attach these fields as metadata to a "TideYear" which is linked to a lake.

**Comment by torbencarstens** [comment]
relates to https://github.com/woog-life/api/issues/124

**Comment by BjoernPetersen** [comment]
Honestly, we kind of don't care about any of that. Timezone information is contained in every line anyway, and we already know what location the data is for. I'll just close this as won't do.
